### ISSUE TITLE
Trying to get food created to go into the meal it is created in, but it only goes to first meal id

### ISSUE THREAD

**Issue by lewisj4** [lewisj4/food_app#1]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

User Story: As a user I want to be able to create a new record of a food contained within the meal so that I have a breakdown of my meal.

Trying to do: I am trying to assign the food that is being created to the meal that it pertains to.

Detailed Description: When I create a new food for a meal that is NOT the first meal the food does not appear. But it will appear in the first meal that was created.

Food Controller Create Function

```
def create
        @food = Food.new(food_params)
        @meal = Meal.find_by(params[:id])
        @food.meal_id = @meal.id
        @meal.foods << @food

        if @food.save!
            redirect_to @food
        else
            render :new
        end     
     end
```

I've tried looking at the rails docs for alternatives to .find because that resulted in no "id" getting assigned to my `@meal`. .find_by got me 1 step further in the sense that it results with an "id" getting assigned to my `@meal` in my create function; however, that "id" is always 1. I also tried using .where but kept getting an "id" equal to nil.

Specifically I would like help with getting my foods assigned and shown under the correct meal.

**Comment by meal** [comment]
LOL, I'm getting notifications as you're mentioning me here ;)

**Comment by harimohanraj89** [comment]
Sorry @meal! We will escape (`@meal`) you in the future!

**Comment by meal** [comment]
thanks ;)

**Comment by harimohanraj89** [comment]
@lewisj4 Make sure to put your instance variables inside backticks `@meal`, `@food`, so that we're not accidentally mentioning other users on GitHub :D

**Comment by harimohanraj89** [comment]
Taken

**Comment by lewisj4** [comment]
No problem, it should be good now.
