### ISSUE TITLE
API calling problems

### ISSUE THREAD

**Issue by lewisj4** [lewisj4/food_app#2]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

User Story: As a user I want to be able to automatically generate the nutritional information so that when I don't know how many calories, etc were in my meal I can get a rough estimate.

I am trying to create a route and a view to assign a Food with only a name it's nutritional breakdown.

I created a route add_info for the FoodsController and a view add_info_food.html.erb and a method for add_info but I can't get the food's id without first saving the food. I'm at a standstill because when I create an instance of a new food it redirects to the foods nutritional breakdown, which renders with the name of the food while the rest of the fields are empty; and I want it so that it will go to the add_info_food.html view where I am trying to submit the name through that and then redirect to a page that has all the needed information.

**Comment by WilliamfShaw** [comment]
@lewisj4 are you getting any errors?

**Comment by lewisj4** [comment]
@WilliamfShaw yah, I get an error `undefined method `gsub' for nil:NilClass`
![screen shot 2015-05-12 at 3 44 53 pm](https://cloud.githubusercontent.com/assets/10853122/7596667/6caaff1a-f8bd-11e4-9dde-1cef96dc997c.png)

**Comment by harimohanraj89** [comment]
This seems to indicate that `term` is nil. You should investigate that.

**Comment by WilliamfShaw** [comment]
@lewisj4 what hari said, term is nil, binding.pry and track down term

**Comment by DrRobotmck** [comment]
Is this still an issue?

**Comment by lewisj4** [comment]
Yah, big issue!
